---
version: "3"

services:
  ldap:
    image: osixia/openldap
    environment:
      - LDAP_DOMAIN=mydomain.tld
    volumes:
      - ./docker/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-boostrap.ldif:ro
      - ./server-ldap-schemas/src/main/resources/oidc-client-schema-openldap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/40-oauth-client.ldif:ro
      - ./server-ldap-schemas/src/main/resources/oidc-session-schema-openldap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/41-oauth-session.ldif:ro
      - ./server-ldap-schemas/src/main/resources/oidc-authz-schema-openldap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/42-oauth-authz.ldif:ro
    command: --copy-service

  oauth:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
