---
version: "3"

services:
  ldap:
    image: osixia/openldap
    environment:
      - LDAP_DOMAIN=mydomain.tld
    volumes:
      - ./docker/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-boostrap.ldif:ro
      - ./schemas/oauth2-client-openldap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/40-oauth2-client.ldif:ro
      - ./schemas/oauth2-authz-openldap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/41-oauth2-authz.ldif:ro
    command: --copy-service

  oauth:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
